export default {
  // Common
  confirmStateChange: 'You will be taken offline and will not receive requests while offline. Are you sure?',
  commonAdmin: 'ADMIN',
  commonAll: 'ALL',
  commonAmount: 'AMOUNT',
  commonBack: 'BACK',
  commonCancel: 'CANCEL',
  commonClr: 'CLR',
  commonDone: 'DONE',
  commonEnd: 'END',
  commonExit: 'EXIT',
  commonHalaal: 'HALAAL',
  commonLoading: 'LOADING',
  commonMenu: 'MENU',
  commonOk: 'OK',
  commonPizza: 'PIZZA',
  commonRegular: 'REGULAR',
  commonRequiredIndicator: '*',
  commonSearch: 'SEARCH',
  commonStart: 'START',
  commonSummary: 'SUMMARY',
  commonTotal: 'TOTAL',
  commonType: 'TYPE',

  // AssignCashier
  assignCashierAssignCashier: 'ASSIGN CASHIER',
  assignCashierOngoingShift: 'ONGOING SHIFT',
  assignCashierCashierAlreadyAssigned: 'THE SELECTED CASHIER IS ALREADY ASSIGNED TO A SHIFT. DO YOU WANT TO CONTINUE FROM THE PREVIOUS?',

  // Cash
  cashCashDrop: 'CASH DROP',
  cashCashFloat: 'CASH FLOAT',
  cashCashMenu: 'CASH MENU',
  cashCashUp: 'CASH UP',
  cashDropError: 'PLEASE TRY THE AGAIN',
  cashOpenDrawer: 'OPEN DRAWER',

  // Cash Float
  cashDropCashDrop: 'CASH DROP',

  // Cash Float
  cashFloatCashFloat: 'CASH FLOAT',
  cashFloatOpenDrawer: 'OPEN DRAWER',

  // Cash Up
  cashUpCash: 'CASH',
  cashUpCashDrops: 'CASH DROPS',
  cashUpCashFloat: 'CASH FLOAT',
  cashUpCashier: 'CASHIER',
  cashUpCashOnHand: 'CASH ON HAND',
  cashUpCashUp: 'CASH UP',
  cashUpCreditCard: 'CREDIT CARD',
  cashUpMrDelivery: 'MR DELIVERY',
  cashUpOrders: 'ORDERS',
  cashUpSales: 'SALES',
  cashUpSummary: 'CASH SUMMARY',
  cashUpTake: 'TAKE',
  cashUpTillId: 'TILL ID',
  cashUpTotal: 'TOTAL',
  cashUpUberEats: 'UBER EATS',
  cashUpVoids: 'VOIDS',
  cashUpVouchers: 'VOUCHERS',
  cashUpOnline: 'ONLINE',
  cashUpCounter : 'COUNTER',
  cashUpDelivery: 'DELIVERY',
  cashUpCollect: 'COLLECT',

  // Customer
  customerCustomer: 'CUSTOMER',
  customerFirstName: 'FIRST NAME',
  customerInvalidMobileNumber: 'Invalid mobile number',
  customerLastName: 'LAST NAME',
  customerMobile: 'MOBILE',
  customerNote: 'NOTE',

  // Discount
  discountApplyDiscount: 'APPLY DISCOUNT',
  discountBirthday: 'BIRTHDAY',
  discountCustom: 'CUSTOM',
  discountDiscount: 'DISCOUNT',
  discountManager: 'MANAGER',
  discountMultiple: 'MULTIPLE',
  discountNo: 'NO',
  discountOwner: 'OWNER COMP',
  discountR100: 'R100 OFF',
  discountR50: 'R50 OFF',
  discountStaff: 'STAFF',

  // Discount Categories //TODO: assess whether this needs to come from an API call
  discountOff: 'OFF',
  discountTypeFixed: 'FIXED',
  discountTypeOther: 'OTHER',
  discountTypePercentage: '%',

  // Error
  errorGenericRequest: 'SOMETHING WENT WRONG. PLEASE TRY AGAIN.',
  errorGenericRequestTitle: 'SOMETHING WENT WRONG',
  errorOngoingShiftBody:'THE CURRENT TILL SHIFT NEEDS TO BE TERMINATED BEFORE STARTING A NEW ONE.',
  errorOngoingShiftTitle: 'ONGOING SHIFT',
  errorStoreOfflineBody:'IT SEEMS THAT YOUR STORE IS OFFLINE. PLEASE TRY AGAIN LATER.',
  errorStoreOfflineTitle: 'OFFLINE STORE',
  errorSubmitOrderBody:'THE ORDER WAS NOT CREATED. MAKE SURE THAT ALL THE DETAILS WERE CORRECTLY CAPTURED.',
  errorSubmitOrderTitle: 'SOMETHING WENT WRONG',
  errorUnassignedTillBody:'TO CREATE ORDERS, A CASHIER NEEDS TO BE ASSIGNED TO THIS TILL.',
  errorUnassignedTillTitle: 'UNASSIGNED TILL',

  // Home
  homeAdminMenu: 'ADMIN MENU',
  homeAdminPin: 'ADMIN PIN',
  homeAssignCashier: 'ASSIGN CASHIER',
  homeCashierPin: 'CASHIER PIN',
  homeOrders: 'ORDERS',
  homeReports: 'REPORTS',
  homeStockManagement: 'STOCK MNGMT',
  homeCashUp: 'CASH UP',
  homeCashUpSuccessful: 'THE STORE CASHUP WAS SUCCESSFUL',
  homeStoreCashUp: 'CASH UP STORE',

  // Note
  noteAddNote: 'ADD NOTE',
  noteNote: 'NOTE',

  // Order
  orderAddOneMorePizza: 'ADD ONE MORE PIZZA',
  orderAddPizza: 'ADD PIZZA',
  orderAllOrders: 'ALL ORDERS',
  orderApplyDiscount: 'APPLY DISCOUNT',
  orderCash: 'CASH',
  orderCashMenu: 'CASH MENU',
  orderChange: 'CHANGE',
  orderCheckout: 'CHECKOUT',
  orderCollect: 'COLLECT',
  orderCompleted: 'COMPLETED',
  orderCounter: 'COUNTER',
  orderCreditCard: 'CREDIT CARD',
  orderCustomer: 'CUSTOMER',
  orderCustomerSearch: 'CUSTOMER SEARCH',
  orderDate: 'DATE',
  orderDelivery: 'DELIVERY',
  orderEft: 'EFT',
  orderEmptyCart: 'EMPTY ORDER',
  orderFilter: 'FILTER',
  orderFilterOff:'FILTER : OFF' ,
  orderIncompleteOrder: 'INCOMPLETE ORDER',
  orderInvalidPizzaBody: 'PIZZA REQUIRES A MINIMUM OF "SIZE" AND "BASE" TO BE ADDED',
  orderInvalidPizzaTitle: 'INVALID PIZZA',
  orderInvalidSaladBody: 'SALAD REQUIRES A DRESSING TO BE ADDED',
  orderInvalidSaladTitle: 'INVALID SALAD',
  orderInvalidSpecialBody: 'MAKE SURE EVERY ITEM IN THE SPECIAL WAS SELECTED',
  orderInvalidSpecialTitle: 'INVALID SPECIAL',
  orderInvalidStarterBody: 'THIS STARTER REQUIRES A TOPPING TO BE ADDED',
  orderInvalidStarterTitle: 'INVALID STARTER',
  orderItem: 'ITEM',
  orderMrDelivery: 'MR DELIVERY',
  orderNewOrder: 'NEW ORDER',
  orderNoAvailableOrders: 'THERE ARE NO ORDERS AVAILABLE',
  orderNote: 'NOTE',
  orderNotMade: 'NOT MADE',
  orderOnline: 'ONLINE',
  orderOrder: 'ORDER',
  orderOrderMenu: 'ORDER MENU',
  orderOrderNumber: 'ORDER#',
  orderOrders: 'ORDERS',
  orderOrderSearch: 'SEARCH',
  orderOrderType: 'ORDER TYPE',
  orderOutstading: 'OUTSTANDING',
  orderPay: 'PAY',
  orderPaymentDetails: 'PAYMENT DETAILS',
  orderPhone: 'PHONE',
  orderPrice: 'PRICE',
  orderReason: 'REASON',
  orderReprint: 'RE-PRINT',
  orderSearchClear : 'CLEAR',
  orderSpecialIncomplete: 'THE SPECIAL IS INCOMPLETE',
  orderStatus: 'STATUS',
  orderTotal: 'TOTAL',
  orderType: 'TYPE',
  orderUberEats: 'UBER EATS',
  orderUnpaid: 'UNPAID',
  orderView: 'VIEW',
  orderViewOrder: 'VIEW\nORDER',
  orderVoidOrder: 'VOID ORDER',
  orderVouchers: 'VOUCHERS',

  // PAYMENT
  paymentCash: 'CASH',
  paymentChange: 'CHANGE',
  paymentCreditCard: 'CREDIT CARD',
  paymentEFT: 'EFT',
  paymentMrDelivery: 'MR DELIVERY',
  paymentOpenDrawer: 'OPEN DRAWER',
  paymentOrderPayment: 'ORDER PAYMENT',
  paymentOther: 'OTHER',
  paymentPaymentDetails: 'PAYMENT DETAILS',
  paymentPlaceholder: '0.00',
  paymentTotal: 'TOTAL',
  paymentUberEats: 'UBER EATS',
  paymentVouchers: 'VOUCHERS',

  // PIN
  pinCorrectPin: 'CORRECT',
  pinEnterPin: 'ENTER PIN',
  pinWrongPin: 'WRONG PIN',

  // Status
  statusStatus: 'STATUS',
  statusStore: 'STORE',
  statusTerminal: 'TERMINAL',
  statusUser: 'USER',
  statusVersion: 'POS VER',

  // Validation
  validationInvalidNumber: 'Invalid number',
  validationInvalidSouthAfricanNumber: 'Must be a South African number',
  validationRequired: 'Required',

  // Void Order
  voidOrderReason: 'REASON',
  voidOrderVoidOrder: 'VOID ORDER',


  //Errors
  fetchAllError : 'An error occured while fetching the commodities.',
  fetchOneError : 'An error occured while fetching the commodity graphing data.',
  brochureReqError : 'An error occured while requesting the brochures.',
  brochureListError : 'An error occured while retrieving the list of brochures.',
  PLATINUM: 'Platinum is a dense, malleable, ductile, highly unreactive, precious, silverish-white transition metal used in catalytic converters, electrical contacts and electrodes and jewelry.',
  GOLD: 'Gold is a reddish-yellow malleable precious metal used for jewelry, electronics, medicine use, cuisine and heat shielding in cars and  space ships.',
  COPPER: 'Copper is a soft, malleable, and ductile metal, is used as a conductor of heat and electricity, as a building material, used in jewelry, coins, and temperature measurement.',
  RARE_EARTH: 'The various uses of rare-earth elements are applicable to the production of high-performance magnets, catalysts, alloys, glasses, and electronics.'

}
