import Opacity from './opacity'

const overlayDark = '#0d1214'
const overlayLight = '#eceff1'

export default {
  alertErrorBackground: '#EC131C',
  alertErrorBorder: '#ffffff',
  alertInfoBackground: '#00ACE2',
  alertInfoBorder: '#ffffff',
  alertWarningBackground: '#E43125',
  alertWarningBorder: '#ffffff',
  black: '#000000',
  lightBlack : '#151415',
  lightGrey : '#f0f0f0f0',
  fieldValidation: '#EC131C',
  focusColor: '#E1E1E1',
  formHightlight: '#6A6A6A',
  overlayDark,
  overlayDark10: `${overlayDark}${Opacity._10}`,
  overlayDark20: `${overlayDark}${Opacity._20}`,
  overlayDark30: `${overlayDark}${Opacity._30}`,
  overlayDark40: `${overlayDark}${Opacity._40}`,
  overlayDark50: `${overlayDark}${Opacity._50}`,
  overlayDark60: `${overlayDark}${Opacity._60}`,
  overlayDark70: `${overlayDark}${Opacity._70}`,
  overlayDark80: `${overlayDark}${Opacity._80}`,
  overlayDark90: `${overlayDark}${Opacity._90}`,
  overlayLight,
  overlayLight10: `${overlayLight}${Opacity._10}`,
  overlayLight20: `${overlayLight}${Opacity._20}`,
  overlayLight30: `${overlayLight}${Opacity._30}`,
  overlayLight40: `${overlayLight}${Opacity._40}`,
  overlayLight50: `${overlayLight}${Opacity._50}`,
  overlayLight60: `${overlayLight}${Opacity._60}`,
  overlayLight70: `${overlayLight}${Opacity._70}`,
  overlayLight80: `${overlayLight}${Opacity._80}`,
  overlayLight90: `${overlayLight}${Opacity._90}`,
  primaryGreen: '#394D1E',
  primaryBlack : '#1c1c1c',
  secondayGreen :'#94C64E',
  secondayLightGreen :'#94C64E',
  secondayLightGrey: '#E0E0E0',
  secondarDarkGrey : '#4C4D4C',
  secondayCharcoal :'#262526',
  textGrey:  '#B3B3B3',
  // tetiaryStone 
  tetiaryGrey : '#7d7d7d7d',
  tetiaryRed :'#C70942',
  romansBorderGrey: '#565556',
  romansDark: '#231F20',
  romansDarkGrey: '#353535',
  romansLightGrey: '#A1A0A0',
  romansMediumLightGrey:'#AEAEAE',
  romansMediumGrey: '#4A4A4A',
  romansNavy: '#00529C',
  romansRed: '#EC131C',
  storeCardBackground: '#6A6A6A',
  success: '#9CCA3F',
  thundora: '#454545',
  transparent: 'transparent',
  unselectedGrey: '#888888',
  primaryOrange : "#F57301",
  white: '#ffffff',
  orange: '#FFA500'
}

// FIXME: Remove colors that are not being used
